### ISSUE TITLE
List Datagrid untuk korelasi One-ToMany

### ISSUE THREAD

**Issue by cucodev** [cucodev/HRIS-R03#5]
Hi Nanda, 
berikut adalah list untuk form employe yg punya grid

1. Dependent
2. Edu
3. Emergency
4. Skill
5. Language
6. Training
7. Certification

untuk form nya masing2 diatas, bentuk nya Popup ....

**Comment by febriinanda** [comment]
maksudnya ini gimana pak?

**Comment by febriinanda** [comment]
Sudah di push
